/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Kiem tra API song + ket noi DB. DB chet -> 503 (khong de 500 lo stack).
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/majors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Majors */
    get: operations["list_majors_api_v1_majors_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/schools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Schools */
    get: operations["list_schools_api_v1_schools_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/schools/{school_slug}/majors/{major_slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Program Detail */
    get: operations["get_program_detail_api_v1_schools__school_slug__majors__major_slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/schools/{school_slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get School Detail */
    get: operations["get_school_detail_api_v1_schools__school_slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/coverage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Coverage */
    get: operations["get_coverage_api_v1_coverage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CityCode
     * @description Ma thanh pho — bang tra cuu `cities`, KHONG phai ENUM Postgres. Enum nay
     *     chi de OpenAPI/FE co union type; test `test_openapi_contract` giu no khop
     *     voi du lieu seed (them thanh pho moi ma quen them vao day -> test do).
     * @enum {string}
     */
    CityCode: "HCM" | "HN";
    /**
     * ConfidenceLevel
     * @enum {string}
     */
    ConfidenceLevel: "verified" | "published_unverified" | "estimated";
    /** CoverageCategoryRowOut */
    CoverageCategoryRowOut: {
      category: components["schemas"]["SchoolCategory"];
      /** Schoolstotal */
      schoolsTotal: number;
      /** Schoolswithdata */
      schoolsWithData: number;
    };
    /** CoverageCityRowOut */
    CoverageCityRowOut: {
      cityCode: components["schemas"]["CityCode"];
      /** Cityname */
      cityName: string;
      /** Schoolstotal */
      schoolsTotal: number;
      /** Schoolswithdata */
      schoolsWithData: number;
    };
    /** CoverageMajorGroupRowOut */
    CoverageMajorGroupRowOut: {
      groupCode: components["schemas"]["MajorGroupCode"];
      /** Groupname */
      groupName: string;
      /** Programswithtuition */
      programsWithTuition: number;
    };
    /** CoverageOut */
    CoverageOut: {
      /** Snapshotdate */
      snapshotDate: string | null;
      totals: components["schemas"]["CoverageTotalsOut"];
      /** Bycity */
      byCity: components["schemas"]["CoverageCityRowOut"][];
      /** Bycategory */
      byCategory: components["schemas"]["CoverageCategoryRowOut"][];
      /** Bymajorgroup */
      byMajorGroup: components["schemas"]["CoverageMajorGroupRowOut"][];
      /** Schools */
      schools: components["schemas"]["CoverageSchoolRowOut"][];
    };
    /** CoverageSchoolRowOut */
    CoverageSchoolRowOut: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Shortname */
      shortName: string | null;
      cityCode: components["schemas"]["CityCode"];
      category: components["schemas"]["SchoolCategory"];
      /** Nprograms */
      nPrograms: number;
      latestSourceDocType: components["schemas"]["SourceDocType"] | null;
      /** Latestsourcedate */
      latestSourceDate: string | null;
      /** Lastupdated */
      lastUpdated: string | null;
    };
    /** CoverageTotalsOut */
    CoverageTotalsOut: {
      /** Schoolstotal */
      schoolsTotal: number;
      /** Schoolswithdata */
      schoolsWithData: number;
      /** Programswithtuition */
      programsWithTuition: number;
      /** Tuitionrecords */
      tuitionRecords: number;
      /** Sourcescited */
      sourcesCited: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthOut
     * @description Pydantic response model — FastAPI dung de validate + sinh OpenAPI schema.
     */
    HealthOut: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded";
      /**
       * Db
       * @enum {string}
       */
      db: "ok" | "down";
    };
    /**
     * IncreaseSourceKind
     * @enum {string}
     */
    IncreaseSourceKind: "published_roadmap" | "default_estimate";
    /**
     * MajorGroupCode
     * @description Ma nhom nganh — bang tra cuu `major_groups`, khop nhu CityCode.
     * @enum {string}
     */
    MajorGroupCode:
      "CNTT" | "KY_THUAT" | "KINH_TE" | "Y_DUOC" | "LUAT" | "LOGISTICS";
    /**
     * MajorOut
     * @description Khop `Major` domain.ts.
     */
    MajorOut: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Code */
      code: string | null;
      groupCode: components["schemas"]["MajorGroupCode"];
      /** Standardyears */
      standardYears: number;
      /** Requirespracticelicense */
      requiresPracticeLicense: boolean;
      /** Practiceprofession */
      practiceProfession: string | null;
    };
    /**
     * MajorRowOut
     * @description Khop `MajorRow` domain.ts — 1 dong o man hinh S1 (`GET /api/v1/majors`).
     */
    MajorRowOut: {
      program: components["schemas"]["ProgramOut"];
      school: components["schemas"]["SchoolOut"];
      major: components["schemas"]["MajorOut"];
      year1: components["schemas"]["TuitionRecordOut"];
      increase: components["schemas"]["ProgramIncreaseOut"] | null;
    };
    /**
     * ProgramDetailOut
     * @description 1 he dao tao (track/language/campus) trong trang chi tiet nganh-truong (S3).
     */
    ProgramDetailOut: {
      program: components["schemas"]["ProgramOut"];
      year1: components["schemas"]["TuitionRecordOut"];
      increase: components["schemas"]["ProgramIncreaseOut"] | null;
      /** Yearlyamounts */
      yearlyAmounts: components["schemas"]["YearlyAmountOut"][];
      /** Totalcourse */
      totalCourse: number;
      /** Totalwithlicense */
      totalWithLicense: number;
    };
    /**
     * ProgramDetailResponseOut
     * @description Khop response cua `GET /api/v1/schools/{school_slug}/majors/{major_slug}` (S3) —
     *     gom TAT CA programs cung (school, major), dung schema.md §3.
     */
    ProgramDetailResponseOut: {
      school: components["schemas"]["SchoolOut"];
      major: components["schemas"]["MajorOut"];
      /** Programs */
      programs: components["schemas"]["ProgramDetailOut"][];
    };
    /**
     * ProgramIncreaseOut
     * @description Khop `ProgramIncrease` domain.ts.
     */
    ProgramIncreaseOut: {
      /** Programid */
      programId: string;
      /** Annualincreasepct */
      annualIncreasePct: number;
      increaseSource: components["schemas"]["IncreaseSourceKind"];
    };
    /**
     * ProgramLanguage
     * @description Cot `programs.language` la `text` (schema.md §2), khong phai ENUM — nhung
     *     van dung enum nay lam kieu Python + nguon cho CHECK constraint.
     * @enum {string}
     */
    ProgramLanguage: "vi" | "en" | "vi_en";
    /**
     * ProgramOut
     * @description Khop `Program` domain.ts — FE dung slug cho school/major, BE dung FK
     *     (join luc build response, khong doi cot DB).
     */
    ProgramOut: {
      /** Id */
      id: string;
      /** Schoolslug */
      schoolSlug: string;
      /** Majorslug */
      majorSlug: string;
      track: components["schemas"]["ProgramTrack"];
      language: components["schemas"]["ProgramLanguage"];
      /** Campus */
      campus: string | null;
      /** Displayname */
      displayName: string | null;
    };
    /**
     * ProgramTrack
     * @description He dao tao — hoc phi chenh 3-5 lan, khong bao gio tron khi tinh trung vi.
     * @enum {string}
     */
    ProgramTrack: "dai_tra" | "chat_luong_cao" | "tien_tien" | "quoc_te";
    /**
     * SchoolCategory
     * @description Gop `type` + `autonomy_status` cua brief thanh 1 enum (schema.md §3 schools).
     * @enum {string}
     */
    SchoolCategory:
      "cong_lap" | "cong_lap_tu_chu" | "tu_thuc" | "tu_thuc_von_nuoc_ngoai";
    /**
     * SchoolDetailResponseOut
     * @description Khop response cua `GET /api/v1/schools/{school_slug}` (F7).
     */
    SchoolDetailResponseOut: {
      school: components["schemas"]["SchoolOut"];
      /** Trackstats */
      trackStats: components["schemas"]["SchoolTrackStatOut"][];
      /** Programs */
      programs: components["schemas"]["SchoolProgramRowOut"][];
    };
    /**
     * SchoolOut
     * @description Khop `School` domain.ts.
     */
    SchoolOut: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Shortname */
      shortName: string | null;
      cityCode: components["schemas"]["CityCode"];
      category: components["schemas"]["SchoolCategory"];
      /** Logourl */
      logoUrl: string | null;
    };
    /**
     * SchoolProgramRowOut
     * @description Khop `SchoolProgramRow` domain.ts — 1 dong trong bang danh sach nganh
     *     cua 1 truong (F7). `year1.source` luon None o day — F12 (nguon) chi hien
     *     o trang F6, khong lap lai o F7 (xem plan Tuan 4).
     */
    SchoolProgramRowOut: {
      program: components["schemas"]["ProgramOut"];
      major: components["schemas"]["MajorOut"];
      year1: components["schemas"]["TuitionRecordOut"];
    };
    /**
     * SchoolRowOut
     * @description Khop `SchoolRow` domain.ts — 1 dong o man hinh S2 (`GET /api/v1/schools`).
     */
    SchoolRowOut: {
      school: components["schemas"]["SchoolOut"];
      stats: components["schemas"]["SchoolStatsOut"];
    };
    /**
     * SchoolStatsOut
     * @description Khop `SchoolStats` domain.ts.
     */
    SchoolStatsOut: {
      /** Nprograms */
      nPrograms: number;
      /** Minamount */
      minAmount: number;
      /** Minmajorname */
      minMajorName: string;
      /** Medianamount */
      medianAmount: number;
      /** Maxamount */
      maxAmount: number;
      /** Maxmajorname */
      maxMajorName: string;
      /** Increasesummary */
      increaseSummary: string;
    };
    /**
     * SchoolTrackStatOut
     * @description Khop `SchoolTrackStat` domain.ts — 1 hang / he dao tao trong 1 truong
     *     (F7 chart Min-Max noi bo truong). Cung VIEW `school_track_stats` voi
     *     SchoolStatsOut nhung loc theo school_id thay vi track — moi truong co toi
     *     da 1 dong / he da co chuong trinh.
     */
    SchoolTrackStatOut: {
      track: components["schemas"]["ProgramTrack"];
      /** Nprograms */
      nPrograms: number;
      /** Minamount */
      minAmount: number;
      /** Minmajorname */
      minMajorName: string;
      /** Medianamount */
      medianAmount: number;
      /** Maxamount */
      maxAmount: number;
      /** Maxmajorname */
      maxMajorName: string;
    };
    /**
     * SourceDocType
     * @enum {string}
     */
    SourceDocType:
      "de_an_tuyen_sinh" | "thong_bao_hoc_phi" | "quy_dinh_nghe" | "khac";
    /**
     * SourceOut
     * @description Khop `Source` domain.ts (F12) — chi gan duoc voi ban ghi CONG BO that
     *     (Nam 1); cac nam du phong la so tinh, khong co source_id that.
     */
    SourceOut: {
      /** Url */
      url: string;
      docType: components["schemas"]["SourceDocType"];
      /** Publisheddate */
      publishedDate: string | null;
    };
    /**
     * TuitionRecordOut
     * @description Khop `TuitionRecord` domain.ts. KHONG lo needs_review/review_reason —
     *     chua co UI hien thi (xem migration 0002 + plan Tuan 2).
     */
    TuitionRecordOut: {
      /** Programid */
      programId: string;
      /** Academicyear */
      academicYear: string;
      /** Amountperyear */
      amountPerYear: number;
      /** Isprojected */
      isProjected: boolean;
      confidence: components["schemas"]["ConfidenceLevel"];
      source: components["schemas"]["SourceOut"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * YearlyAmountOut
     * @description 1 nam trong bang hoc phi tinh luy tien cua 1 program (S3) — so **tinh**,
     *     khong phai ban ghi DB (khac TuitionRecordOut: khong co program_id/confidence).
     */
    YearlyAmountOut: {
      /** Academicyear */
      academicYear: string;
      /** Amountperyear */
      amountPerYear: number;
      /** Isprojected */
      isProjected: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthOut"];
        };
      };
    };
  };
  list_majors_api_v1_majors_get: {
    parameters: {
      query?: {
        /** @description Loc theo TEN TRUONG + ten viet tat + TEN NGANH (khop bat ky), bo dau, khong phan biet hoa/thuong. Toi thieu 2 ky tu sau khi chuan hoa; ngan hon -> tra []. */
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MajorRowOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_schools_api_v1_schools_get: {
    parameters: {
      query?: {
        /** @description Loc theo TEN TRUONG + ten viet tat, bo dau, khong phan biet hoa/thuong. Toi thieu 2 ky tu sau khi chuan hoa; ngan hon -> tra []. */
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolRowOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_program_detail_api_v1_schools__school_slug__majors__major_slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        school_slug: string;
        major_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramDetailResponseOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_school_detail_api_v1_schools__school_slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        school_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolDetailResponseOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_coverage_api_v1_coverage_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoverageOut"];
        };
      };
    };
  };
}
